call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" ---------------------------------------------------------------------------
" General
" ---------------------------------------------------------------------------

syntax on
filetype plugin indent on

" ---------------------------------------------------------------------------
" Colors / Theme / Font
" ---------------------------------------------------------------------------

colorscheme solarized
set background=dark
set guifont=Monaco:h13			" Set the font

" ---------------------------------------------------------------------------
" UI
" ---------------------------------------------------------------------------

set guioptions-=T 				" Hide the toolbar
set lines=35 columns=120 		" Set the window size
set nowrap						" Turn word wrapping off. :set wrap turns it back on.
set nu!							" Turn on line numbers
set tabstop=4					" Set tab width to four
set tabpagemax=50 				" Increase the number of allowed tabs
set showtabline=2 				" Always show the tabline
set guioptions-=L				" Disable left scrollbar
set guioptions-=r				" Disable right scrollbar
set ruler						" Turn on row,column dislay on status bar
set backspace=2           		" Allow backspacing over everything in insert mode
set whichwrap+=<,>,h,l,[,] 		" Backspace and cursor keys wrap to
let macvim_hig_shift_movement=1 " Turn on selection via shift+arrow keys

" ---------------------------------------------------------------------------
" Shortcut Keys
" ---------------------------------------------------------------------------

" Map tab to indent
vmap <Tab> >gv		

" Map shift+tab to unindent
vmap <S-Tab> <gv

" Toggle nerdtree
map <F2> :NERDTreeToggle<CR>

" F12 to reload vimrc
map <F12> :source $MYVIMRC <CR>

" ----------------------------------------------------------------------------
" Backups
" ----------------------------------------------------------------------------

set nobackup                           " do not keep backups after close
set nowritebackup                     " do not keep a backup while working
set noswapfile                        " don't keep swp files either
set backupdir=~/.vim/backup  	       " store backups under ~/.vim/backup
set backupcopy=yes                     " keep attributes of original file
set directory=~/.vim/swap		       " keep swp files under ~/.vim/swap

" ----------------------------------------------------------------------------
" Sessions
" ----------------------------------------------------------------------------

function! RestoreSession()
  if argc() == 0 "vim called without arguments
    execute 'source ~/.vim/session'
  end
endfunction

function! SaveSession()
  if argc() == 0 "vim called without arguments
	execute 'mksession! ~/.vim/session'
  end
endfunction

autocmd VimEnter * call RestoreSession()
autocmd VimLeave * call SaveSession()
