# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dustin"
plugins=(git osx)
source $ZSH/oh-my-zsh.sh

# Include other files
source ~/.aliases

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Make sure Homebrew's packages before others
export PATH="/usr/local/bin:$PATH"

# Ruby Options
export RUBYOPT=rubygems