# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dustin"
plugins=(git osx)
source $ZSH/oh-my-zsh.sh

# Include other files
source ~/.aliases

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# ColdFusion 10
export PATH="/Applications/ColdFusion10/cfusion/bin:$PATH"

# Make sure Homebrew's packages before others
export PATH="/usr/local/bin:$PATH"

# Ruby Options
export RUBYOPT=rubygems

# Autojump
if [ -f `brew --prefix`/etc/autojump ]; then
  . `brew --prefix`/etc/autojump
fi